### PR TITLE
Bugifx paths in file_nonOverlap_reOrg

### PR DESCRIPTION
**Pull request by BorjaRequena**
Minor bugfix to properly handle paths in `file_nonOverlap_reOrg` when generating challenge datasets.

### CODE REVIEW

**Comment by BorjaRequena** [comment]
This PR also resolves #29

**Comment by gorkamunoz** [comment]
Borja, what happens now if we input the folders as `str` to `file_nonOverlap_reOrg`? I understand that it must now be a Path and not a string, because if not the `/` operation to merge paths will fail? 

See that the input that comes from dataset_challenge (variable `path` there) will be a string. I understand that we have to take care of that before sending it to `file_nonOverlap_reOrg`?

**Comment by BorjaRequena** [comment]
Since `file_nonOverlap_reOrg` is only called from `dataset_challenge`, I ensured that it always passes in a `Path` object. When used anywhere else, we should take this into account. We can always add a double-check at the beginning of this function to transform the input to `Path`, although whoever's developing or using it can simply account for this type restriction. I can open a quick PR implementing it, if you think it'll make our lives easier @gorkamunoz 😄

**Comment by gorkamunoz** [comment]
I think it is fine to leave it like this. You are right that within the library (as far as I remember), we only call it in `challenge_dataset_phenom`. I use it sometimes as standalone, but if properly documented, is easy to see that we now need to inputs paths.

**Pull request merged**
